import Footer from "@/components/common/footer/footer";
import Layout from "@/components/common/layout/layout";
import LearningResourcesIntro from "@/components/learningResources/learningResoucesIntro/learningResourcesIntro";
import { NextPage } from "next"
import Head from "next/head";
import { footerData } from "@/constants/footer";


const LearningResourcesPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Learning Resources | Raena Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <LearningResourcesIntro />
                <Footer data={footerData} />
            </Layout>
        </>
    )
}

export default LearningResourcesPage;