import AboutImages from "@/components/about/aboutImages";
import AboutIntro from "@/components/about/aboutIntro";
import CompetitiveAdvantage from "@/components/about/competitiveAdvantage";
import OurStory from "@/components/about/ourStory";
import WhatWeDo from "@/components/about/whatWeDo";
import Footer from "@/components/common/footer/footer";
import Layout from "@/components/common/layout/layout";
import { footerData } from "@/constants/footer";
import { NextPage } from "next"; 
import Head from "next/head";


const AboutPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>About Us | Raena Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <AboutIntro />
                <AboutImages />
                <WhatWeDo />
                <CompetitiveAdvantage />
                <OurStory />
                <Footer data={footerData} />
            </Layout>
        </>
    )
}

export default AboutPage;