import Layout from "@/components/common/layout/layout";
import { NextPage } from "next"
import Head from "next/head";


const BookOnlinePage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Book Online | Raena Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                
            </Layout>
        </>
    )
}

export default BookOnlinePage;