import Footer from "@/components/common/footer/footer";
import Layout from "@/components/common/layout/layout";
import ContactUs from "@/components/contact/contactUs";
import TellUs from "@/components/contact/tellUs";
import { footerData } from "@/constants/footer";
import { NextPage } from "next"
import Head from "next/head";


const FaqPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Contact us | Raena Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <ContactUs />
                <TellUs />
                <Footer data={footerData} />
            </Layout>
        </>
    )
}

export default FaqPage;