import Footer from '@/components/common/footer/footer';
import Hero from '@/components/home/hero/hero';
import PreparingStudents from '@/components/home/preparingStudents/preparingStudents';
import Testimonials from '@/components/home/testimonials/testimonials';
import Wave from '@/components/home/wave/wave';
import WhatWeOffer from '@/components/home/whatWeOffer/whatWeOffer';
import WhatWeProvide from '@/components/home/whatWeProvide/whatWeProvide';
import Layout from '@/components/common/layout/layout';
import { footerData } from '@/constants/footer';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Raena Learning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout>
        <Hero />
        <Wave />
        <WhatWeOffer />
        <PreparingStudents />
        <WhatWeProvide />
        <Testimonials />
        <Footer data={footerData} />
     </Layout>
    </>
  )
}
