import BlogsCards from "@/components/blogs/blogCards";
import BlogIntro from "@/components/blogs/blogsIntro";
import Footer from "@/components/common/footer/footer";
import Layout from "@/components/common/layout/layout";
import { NextPage } from "next"
import Head from "next/head";
import { footerData } from "@/constants/footer";

const AllBlogsPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>All Blogs | Raena Learning</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <BlogIntro />
                <BlogsCards />
                <Footer data={footerData} />
            </Layout>
        </>
    )
}

export default AllBlogsPage;